import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale, getMessages } from 'next-intl/server'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import { ThemeProvider } from '@mui/system'
import CssBaseline from '@mui/material/CssBaseline'
import Box from '@mui/material/Box'

import { theme } from '@/styles/app-theme/custom-mui.styles'
import Sidebar from '@/containers/sidebar'
import getCurrentUser from '@/utils/get-current-user'
import Header from '@/containers/header'

import styles from './styles'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  const locale = await getLocale()
  const messages = await getMessages()

  const user = await getCurrentUser()

  const containerStyle = user ? styles.container('basic.white') : styles.container('backgroundColor')
  const headerContainerStyle = user ? styles.headerContainer({
    isAbsolute: false,
    backgroundColor: 'backgroundColor',
  }) : styles.headerContainer({
    isAbsolute: true,
    backgroundColor: 'transparent',
  })

  return (
    <html lang={locale}>
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <NextIntlClientProvider messages={messages}>
              <Box sx={containerStyle}>
                <Box sx={headerContainerStyle}>
                  <Header user={user} />
                </Box>
                
                <Sidebar user={user}>
                  {children}
                </Sidebar>
              </Box>
            </NextIntlClientProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}

export default RootLayout
